### ISSUE TITLE
Incompatible with Trashslot while using a GUI resourcepack

### ISSUE THREAD

**Issue by Jakobabs** [IMB11-Mods/Flow#17] opened 2024-03-05 05:34 UTC
Trash slot is broken when using this mod. The opening animation somehow messes where the trashslot is supposed to be anchored to, probably either positioning it off screen or under the UI

Posted issue on Trashslot, https://github.com/TwelveIterationMods/TrashSlot/issues/130

**Comment by Killercrab432** [comment] 2024-03-06 09:41
I think it might be an imcompatibility with any resource packs that tweak the inventory, it works fine together when using no resource pack but when i use a dark gui resource pack the trash slot disappears

**Comment by Jakobabs** [comment] 2024-03-08 02:11
@Killercrab432 I use dark gui too and never thought to try that! That's so weird given that it's a resourcepack. Ill update the post. Thanks

**Comment by IMB11** [comment] 2024-08-09 16:42
Closing this as cannot reproduce with 2.0.0

**Closed by IMB11** 2024-08-09 16:42 UTC
Labels: bug, invalid
